# Generated by Django 4.2.4 on 2023-08-23 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0001_squashed_0003_order_assembled_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="firstname",
            field=models.CharField(default="", max_length=50, verbose_name="Имя"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="client",
            name="lastname",
            field=models.CharField(default="", max_length=50, verbose_name="Фамилия"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="client",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="", max_length=128, region="RU", verbose_name="Номер телефона"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="client",
            name="user",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="courier",
            name="firstname",
            field=models.CharField(default="", max_length=50, verbose_name="Имя"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="courier",
            name="lastname",
            field=models.CharField(default="", max_length=50, verbose_name="Фамилия"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="courier",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="", max_length=128, region="RU", verbose_name="Номер телефона"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="courier",
            name="user",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courier",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="florist",
            name="firstname",
            field=models.CharField(default="", max_length=50, verbose_name="Имя"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="florist",
            name="lastname",
            field=models.CharField(default="", max_length=50, verbose_name="Фамилия"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="florist",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="", max_length=128, region="RU", verbose_name="Номер телефона"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="florist",
            name="user",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="florist",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
