# Generated by Django 4.2.4 on 2023-08-23 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_client_firstname_client_lastname_client_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"verbose_name": "Клиент", "verbose_name_plural": "Клиенты"},
        ),
        migrations.AlterModelOptions(
            name="courier",
            options={"verbose_name": "Курьер", "verbose_name_plural": "Курьеры"},
        ),
        migrations.AlterModelOptions(
            name="florist",
            options={"verbose_name": "Флорист", "verbose_name_plural": "Флористы"},
        ),
    ]
