# Generated by Django 4.2.4 on 2023-08-24 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0005_alter_client_options_alter_courier_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.IntegerField(
                        choices=[(1, "Клиент"), (2, "Курьер"), (3, "Флорист")],
                        default=1,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Роль пользователя",
                "verbose_name_plural": "Роли пользователей",
            },
        ),
        migrations.RemoveField(
            model_name="courier",
            name="user",
        ),
        migrations.RemoveField(
            model_name="florist",
            name="user",
        ),
        migrations.CreateModel(
            name="ShopUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region="RU", verbose_name="Номер телефона"
                    ),
                ),
                (
                    "roles",
                    models.ManyToManyField(
                        related_name="shop_users",
                        to="shop.userrole",
                        verbose_name="Роли",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь магазина",
                "verbose_name_plural": "Пользователи магазина",
            },
        ),
        migrations.AlterField(
            model_name="order",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="client_orders",
                to="shop.shopuser",
                verbose_name="клиент",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="courier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courier_orders",
                to="shop.shopuser",
                verbose_name="курьер",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="florist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="florist_orders",
                to="shop.shopuser",
                verbose_name="флорист",
            ),
        ),
        migrations.DeleteModel(
            name="Client",
        ),
        migrations.DeleteModel(
            name="Courier",
        ),
        migrations.DeleteModel(
            name="Florist",
        ),
    ]
