# Generated by Django 4.2.4 on 2023-08-24 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0006_userrole_remove_courier_user_remove_florist_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopuser",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shop_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
