# Generated by Django 4.2.4 on 2023-08-25 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_shopuser_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('lower_limit', models.PositiveSmallIntegerField(verbose_name='Минимальная цена')),
                ('upper_limit', models.PositiveSmallIntegerField(verbose_name='Максимальная цена')),
            ],
            options={
                'verbose_name': 'Фильтр цен',
                'verbose_name_plural': 'Фильтры цен',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(limit_choices_to={'roles__role': 1}, on_delete=django.db.models.deletion.PROTECT, related_name='client_orders', to='shop.shopuser', verbose_name='клиент'),
        ),
        migrations.AlterField(
            model_name='order',
            name='courier',
            field=models.ForeignKey(blank=True, limit_choices_to={'roles__role': 2}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courier_orders', to='shop.shopuser', verbose_name='курьер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='florist',
            field=models.ForeignKey(blank=True, limit_choices_to={'roles__role': 3}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='florist_orders', to='shop.shopuser', verbose_name='флорист'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='описание'),
        ),
    ]
