# Generated by Django 4.2.4 on 2023-08-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_order_delivery_time_range"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_time_range",
            field=models.IntegerField(
                choices=[
                    (0, "Как можно скорее"),
                    (1, "c 10:00 до 12:00"),
                    (2, "c 12:00 до 14:00"),
                    (3, "c 14:00 до 16:00"),
                    (4, "c 16:00 до 18:00"),
                    (5, "c 18:00 до 20:00"),
                ],
                default=0,
                verbose_name="Диапазон времени доставки",
            ),
        ),
    ]
